#!/bin/bash

brew() {
    if [[ "$(uname -s)" == "Darwin" ]]; then
        HOMEBREW_PREFIX=${HOMEBREW_PREFIX:-"/opt/homebrew"}
        "${HOMEBREW_PREFIX}"/bin/brew "$@"
        return
    fi

    if [[ ${HOMEBREW_PREFIX:-} == "" ]]; then
        export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
        export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
        export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"
    fi
    # sudo use -E to preserve-env
    # su use -p to preserve-env
    sudo -E su -p - linuxbrew bash -c "${HOMEBREW_PREFIX}/bin/brew $*"
}
