#!/bin/bash

brew() {
    if [[ "$(uname -s)" == "Darwin" ]]; then
        /usr/local/bin/brew "$@"
        return
    fi

    if [[ ${HOMEBREW_PREFIX:-} == "" ]]; then
        export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
        export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
        export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"
    fi
    sudo su - linuxbrew bash -c "${HOMEBREW_PREFIX}/bin/brew $*"
}
