#!/bin/bash
# show current user@host:pwd for scp
function crt() {
    user="$(whoami)"
    host="$(ifconfig | grep "inet " | grep -v 127.0.0.1 | cut -d " " -f 2)"
    PWD="$(pwd)"

    if [[ $# == 1 ]]; then
        suffix="/$1"
        #statements
    else
        suffix=""
    fi

    echo ${user}@${host}:${PWD}${suffix}
}
