#!/bin/bash

datetime() {
    if [[ "$(uname -s)" == "Darwin" ]] && command_exists gdate; then
        time=$(gdate +%s.%N)
    else
        time=$(date +%s.%N)
    fi
    if [[ ${time: -1} == "N" ]]; then
        # BSD date does not support N
        echo "${time/%N/000000000}"
        return
    fi

    echo "${time}"
}
