#!/bin/bash

# Copyright 2022 jim.zoumo@gmail.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

goenv() {
    local go_target=$1

    go_now=$(go version | cut -d " " -f 3)
    go_now=${go_now#go}
    go_now=${go_now%.*}

    go_latest=$(brew info go | head -1 | cut -d " " -f 3)
    go_latest=${go_latest%.*}

    brew_go_version="go@${go_now}"

    if [[ "${go_now}" == "${go_latest}" ]]; then
        brew_go_version="go"
    fi

    if [[ "${go_target}" == "go@${go_latest}" ]]; then
        go_target="go"
    fi

    if [[ "${brew_go_version}" == "${go_target}" ]]; then
        echo "brew go version is ${go_target} now"
        echo "${go_target}" >"${HOME}/.brew_go_version"
    else
        echo "switch brew go version to ${go_target}"
        brew unlink "${brew_go_version}"
        brew link --force "${go_target}"
        echo "${go_target}" >"${HOME}/.brew_go_version"
        source "${HOME}/.zshrc"
    fi

}
