#!/bin/bash
#
# bootstrap installs things.

echo ""
echo "                       _oo0oo_"
echo "                      o8888888o"
echo "                      88' . '88"
echo "                      (| -_- |)"
echo "                      0\  =  /0"
echo "                    ___/\`---'\\___"
echo "                  .' \\\\\\|     |# '."
echo "                 / \\\\\\|||  :  |||# \\"
echo "               / _||||| -:- |||||- \\"
echo "               |   | \\\\\\\\\\  -  #/ |   |"
echo "               | \\_|  ''\\---/''  |_/ |"
echo "               \\  .-\\__  '-'  ___/-. /"
echo "             ___'. .'  /--.--\\  \`. .'___"
echo "          .'' '<  \`.___\\_<|>_/___.' >' ''."
echo "         | | :  \`- \\\`.;\`\\ _ /\`;.\`/ - \` : | |"
echo "         \\  \\ \`_.   \\_ __\\ /__ _/   .-\` /  /"
echo "     =====\`-.____\`.___ \\_____/___.-\`___.-'====="
echo "                       \`=---='"
echo ""
echo "               佛祖保佑         永無BUG"
echo ""
echo "     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo ""
echo ""

source $(dirname $(dirname ${BASH_SOURCE}))/framework/oo-bootstrap.sh

import util/tryCatch

# enable basic logging for this file by declaring a namespace
namespace bootstrap
# make the Log method direct everything in the namespace 'myApp' to the log handler called DEBUG
Log::AddOutput bootstrap NOTE

export DOT_MODE=${1:-full}

try
{
    bash ./script/dot
    bash ./script/linkfile
}
catch
{
    e="error installing dependencies" throw
}

Log "The installation is complete !!"

default_shell="fish"
TEST_CURRENT_SHELL=$(expr "$SHELL" : '.*/\(.*\)')
shell_bin=$(grep "/${default_shell}$" /etc/shells | tail -1)
if [ "$TEST_CURRENT_SHELL" != "${default_shell}" ]; then
    # If this platform provides a "chsh" command (not Cygwin), do it, man!
    if Command::Exists chsh; then
        Log "Time to change your default shell to ${shell_bin}!"
        sudo chsh -s "${shell_bin}" "$(whoami)"
        # Else, suggest the user do so manually.
    else
        Log "I can't change your shell automatically because this system does not have chsh."
        Log "Please manually change your default shell to ${shell_bin}!"
    fi
fi

[[ -n ${shell_bin} ]] && ${shell_bin}
