#!/bin/bash
#
# bootstrap installs things.

echo ""
echo "                       _oo0oo_"
echo "                      o8888888o"
echo "                      88' . '88"
echo "                      (| -_- |)"
echo "                      0\  =  /0"
echo "                    ___/\`---'\\___"
echo "                  .' \\\\\\|     |# '."
echo "                 / \\\\\\|||  :  |||# \\"
echo "               / _||||| -:- |||||- \\"
echo "               |   | \\\\\\\\\\  -  #/ |   |"
echo "               | \\_|  ''\\---/''  |_/ |"
echo "               \\  .-\\__  '-'  ___/-. /"
echo "             ___'. .'  /--.--\\  \`. .'___"
echo "          .'' '<  \`.___\\_<|>_/___.' >' ''."
echo "         | | :  \`- \\\`.;\`\\ _ /\`;.\`/ - \` : | |"
echo "         \\  \\ \`_.   \\_ __\\ /__ _/   .-\` /  /"
echo "     =====\`-.____\`.___ \\_____/___.-\`___.-'====="
echo "                       \`=---='"
echo ""
echo "               佛祖保佑         永無BUG"
echo ""
echo "     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo ""
echo ""

source $(dirname $(dirname ${BASH_SOURCE}))/framework/oo-bootstrap.sh

import util/tryCatch

# enable basic logging for this file by declaring a namespace
namespace bootstrap
# make the Log method direct everything in the namespace 'myApp' to the log handler called DEBUG
Log::AddOutput bootstrap NOTE

install_ohmyzsh() {
    Log 'Installing oh-my-zsh...'
    # sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    git::clone https://github.com/robbyrussell/oh-my-zsh.git ${HOME}/.oh-my-zsh

    ZSH_CUSTOM="${HOME}/.oh-my-zsh/custom"
    git::clone https://github.com/denysdovhan/spaceship-prompt.git "${ZSH_CUSTOM}/themes/spaceship-prompt"
    ln -sf "${ZSH_CUSTOM}/themes/spaceship-prompt/spaceship.zsh-theme" "${ZSH_CUSTOM}/themes/spaceship.zsh-theme"

    git::clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
}

install_dotfiles() {
    Log 'Installing dotfiles...'

    local overwrite_all=false backup_all=false skip_all=false
    for src in $(find "$DOT_ROOT/" -maxdepth 2 -name '*.symlink'); do
        dst="$HOME/.$(basename "${src%.*}")"
        util::link_file "$src" "$dst"
    done
}

install_ohmyzsh
install_dotfiles

target=${1:-all}
try
{
    if [[ ${target} == "mini" ]]; then
        bash ./script/mini
    else
        bash ./script/dot
    fi
}
catch
{
    e="error installing dependencies" throw
}

Log "The installation is complete !!"

TEST_CURRENT_SHELL=$(expr "$SHELL" : '.*/\(.*\)')
if [ "$TEST_CURRENT_SHELL" != "zsh" ]; then
    # If this platform provides a "chsh" command (not Cygwin), do it, man!
    if Command::Exists chsh; then
        Log "Time to change your default shell to zsh!"
        chsh -s $(grep "/zsh$" /etc/shells | tail -1)
        # Else, suggest the user do so manually.
    else
        Log "I can't change your shell automatically because this system does not have chsh."
        Log "Please manually change your default shell to zsh!"
    fi
fi

env zsh
