#!/bin/bash
#
# dot
#
# `dot` handles installation, updates, things like that. Run it periodically
# to make sure you're on the latest and greatest.

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset
# Catch the error in pipeline.
set -o pipefail

ROOT_PATH="$(dirname $(dirname ${BASH_SOURCE}))"
source ${ROOT_PATH}/lib/init.sh

cd ${DOT_ROOT}

log::status "preparing the operating system"
./os/prepare.sh
log::status "The operating system is ready"

installers=($(util::find_installer | tr " " "\n"))

lang=("python ruby go")

# insatll language support
for installer in ${installers[@]}; do
	if [[ ${lang[@]} =~ ${installer} ]]; then
		log::status "${installer} installing"
		bash $HOME/.dotfiles/${installer}/install.sh
		log::status "${installer} installation is complete"
	fi
done

# install others
for installer in ${installers[@]}; do
	if [[ ${lang[@]} =~ ${installer} ]]; then
		# skip os and python
		continue
	fi
	log::status "${installer} installing"
	bash $HOME/.dotfiles/${installer}/install.sh
	log::status "${installer} installation is complete"
done

cd -
