#!/bin/bash
#
# dot
#
# `dot` handles installation, updates, things like that. Run it periodically
# to make sure you're on the latest and greatest.

source $(dirname $(dirname ${BASH_SOURCE}))/framework/oo-bootstrap.sh
# enable basic logging for this file by declaring a namespace
namespace bootstrap
# make the Log method direct everything in the namespace 'myApp' to the log handler called DEBUG
Log::AddOutput bootstrap NOTE

cd ${DOT_ROOT}

# do minimize installation 
Log "preparing the operating system"
bash ./os/prepare.sh
Log "The operating system is ready"

installers=($(util::find_installer | tr " " "\n"))

lang=("python ruby go")

# insatll language support
for installer in ${installers[@]}; do
    if [[ ${lang[@]} =~ ${installer} ]]; then
        Log "${installer} installing"
        bash $HOME/.dotfiles/${installer}/install.sh
        Log "${installer} installation is complete"
    fi
done

# install others
for installer in ${installers[@]}; do
    if [[ ${lang[@]} =~ ${installer} ]]; then
        # skip os and python
        continue
    fi
    Log "${installer} installing"
    bash $HOME/.dotfiles/${installer}/install.sh
    Log "${installer} installation is complete"
done

cd -
