#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    # 使用 airline 代替原生的 statusline, 记得关闭下面的 statusline
    # statusline_separator = "arrow"
    # statusline_inactive_separator = "arrow"
    # enable_statusline_mode = false

    # 启用 ASCII  
    statusline_unicode_symbols = false
    
    buffer_index_type = 4
    enable_tabline_filetype_icon = true

    # 中文文档
    vim_help_language = "cn"
    snippet_engine = "ultisnips"

    bootstrap_before = "customize#before"
    # bootstrap_after = "customize#after"

    # enable_vimfiler_gitstatus = true

[[custom_plugins]]
  name = "sonph/onehalf"
  merged = 0

[[layers]]
    name = 'core#statusline'
    enable = false

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "VersionControl"

[[layers]]
    name = "chinese"

[[layers]]
    name = "fzf"

[[layers]]
    name = "lang#go"

[[layers]]
    name = "lang#dockerfile"

[[layers]]
    name = "ui"
